version: 2

models:
  - name: int_cases_vaccinations
    description: "Intermediate table joining COVID data, vaccination, population, and state info"
    columns:
      - name: state_abbr
        description: "Two-letter state code"
        tests:
          - not_null
          - unique
      - name: total_cases
        description: "Total COVID cases reported for the week"
      - name: new_cases
        description: "New COVID cases reported for the week"
      - name: population
        description: "Population of the state from Census data"