services:
  airflow:
    build: .
    command: standalone
    ports:
      - "8081:8080"
    env_file: .env
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - PYTHONPATH=/opt/airflow/workspace/src
      - AIRFLOW_CONN_SNOWFLAKE_DEFAULT=${AIRFLOW_CONN_SNOWFLAKE_DEFAULT}
      - DBT_PROFILES_DIR=/opt/airflow/airflow_covid_19_vb
    volumes:
      - .:/opt/airflow/workspace
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./airflow_covid_19_vb:/opt/airflow/airflow_covid_19_vb
      - C:\Users\TitanUp\.dbt\profiles.yml:/opt/airflow/workspace/airflow_covid_19_vb/profiles.yml
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://localhost:8080/api/v2/version" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
