[project]
name = "covid-19-vb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "apache-airflow>=3.1.8",
    "dbt-snowflake>=1.11.3",
    "loguru>=0.7.3",
    "pandas>=3.0.1",
    "pendulum>=3.2.0",
    "plotly>=6.6.0",
    "pydantic-settings>=2.13.1",
    "requests>=2.33.0",
    "snowflake-connector-python>=4.3.0",
    "streamlit>=1.40.0",
]

[project.scripts]
covid-19-vb = "covid_19_vb:main"


[build-system]
requires = ["uv_build>=0.8.13,<0.9.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ruff>=0.15.1",
]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ["E", "F", "I", "W", "N", "UP", "B", "S", "SIM", "RUF", "T20"]

