version: 2

models:
  - name: raw_covid_cases
    description: "Raw COVID-19 cases table"
    columns:
      - name: report_date
        description: "Date of the report"
        
      - name: state
        description: "State abbreviation"