version: 2

sources:
  - name: raw
    database: COVID_DB
    schema: RAW
    tables:
      - name: CDC_WEEKLY_CASES
      - name: CENSUS_POPULATION
      - name: COVID_VACCINATION
      - name: STATE_MAPPING