import os
import snowflake.connector
from dotenv import load_dotenv
from loguru import logger

# Load Snowflake credentials from environment variables
load_dotenv()

SNOWFLAKE_USER = os.getenv("SNOWFLAKE_USER")
SNOWFLAKE_PASSWORD = os.getenv("SNOWFLAKE_PASSWORD")
SNOWFLAKE_ACCOUNT = os.getenv("SNOWFLAKE_ACCOUNT")
SNOWFLAKE_WAREHOUSE = os.getenv("SNOWFLAKE_WAREHOUSE")


def setup_snowflake_environment(conn):
    snowflake = conn.cursor()

    # Create Database & Schemas
    snowflake.execute("CREATE DATABASE IF NOT EXISTS COVID_DB")
    snowflake.execute("USE DATABASE COVID_DB")

    snowflake.execute("CREATE SCHEMA IF NOT EXISTS RAW")
    snowflake.execute("CREATE SCHEMA IF NOT EXISTS STAGING")
    snowflake.execute("CREATE SCHEMA IF NOT EXISTS INTERMEDIATE")


    snowflake.execute("""
    CREATE TABLE IF NOT EXISTS RAW.COVID_VACCINATION (
        DATE TIMESTAMP_NTZ,
MMWR_WEEK VARCHAR,
LOCATION VARCHAR,
ADMINISTERED BIGINT,
ADMINISTERED_5PLUS BIGINT,
ADMINISTERED_12PLUS BIGINT,
ADMINISTERED_18PLUS BIGINT,
ADMINISTERED_65PLUS BIGINT,

ADMINISTERED_JANSSEN BIGINT,
ADMINISTERED_MODERNA BIGINT,
ADMINISTERED_PFIZER BIGINT,
ADMINISTERED_NOVAVAX BIGINT,
ADMINISTERED_UNK_MANUF BIGINT,

ADMINISTERED_BIVALENT BIGINT,
ADMIN_BIVALENT_MOD BIGINT,
ADMIN_BIVALENT_PFR BIGINT,

ADMINISTERED_DOSE1_RECIP BIGINT,
ADMINISTERED_DOSE1_RECIP_5PLUS BIGINT,
ADMINISTERED_DOSE1_RECIP_12PLUS BIGINT,
ADMINISTERED_DOSE1_RECIP_18PLUS BIGINT,
ADMINISTERED_DOSE1_RECIP_65PLUS BIGINT,

ADMINISTERED_DOSE1_POP_PCT FLOAT,
ADMINISTERED_DOSE1_RECIP_5PLUSPOP_PCT FLOAT,
ADMINISTERED_DOSE1_RECIP_12PLUSPOP_PCT FLOAT,
ADMINISTERED_DOSE1_RECIP_18PLUSPOP_PCT FLOAT,
ADMINISTERED_DOSE1_RECIP_65PLUSPOP_PCT FLOAT,

SERIES_COMPLETE_YES BIGINT,
SERIES_COMPLETE_POP_PCT FLOAT,

SERIES_COMPLETE_5PLUS BIGINT,
SERIES_COMPLETE_12PLUS BIGINT,
SERIES_COMPLETE_18PLUS BIGINT,
SERIES_COMPLETE_65PLUS BIGINT,

SERIES_COMPLETE_5PLUSPOP_PCT FLOAT,
SERIES_COMPLETE_12PLUSPOP FLOAT,
SERIES_COMPLETE_18PLUSPOP FLOAT,
SERIES_COMPLETE_65PLUSPOP FLOAT,

SERIES_COMPLETE_JANSSEN BIGINT,
SERIES_COMPLETE_JANSSEN_12PLUS BIGINT,
SERIES_COMPLETE_JANSSEN_18PLUS BIGINT,
SERIES_COMPLETE_JANSSEN_5PLUS BIGINT,
SERIES_COMPLETE_JANSSEN_65PLUS BIGINT,

SERIES_COMPLETE_MODERNA BIGINT,
SERIES_COMPLETE_MODERNA_12PLUS BIGINT,
SERIES_COMPLETE_MODERNA_18PLUS BIGINT,
SERIES_COMPLETE_MODERNA_5PLUS BIGINT,
SERIES_COMPLETE_MODERNA_65PLUS BIGINT,

SERIES_COMPLETE_PFIZER BIGINT,
SERIES_COMPLETE_PFIZER_12PLUS BIGINT,
SERIES_COMPLETE_PFIZER_18PLUS BIGINT,
SERIES_COMPLETE_PFIZER_5PLUS BIGINT,
SERIES_COMPLETE_PFIZER_65PLUS BIGINT,

SERIES_COMPLETE_NOVAVAX BIGINT,
SERIES_COMPLETE_UNK_MANUF BIGINT,
SERIES_COMPLETE_UNK_MANUF_1 BIGINT,
SERIES_COMPLETE_UNK_MANUF_2 BIGINT,
SERIES_COMPLETE_UNK_MANUF_3 BIGINT,
SERIES_COMPLETE_UNK_MANUF_5 BIGINT,
SERIES_COMPLETE_UNK_MANUF_5PLUS BIGINT,

ADDITIONAL_DOSES BIGINT,
ADDITIONAL_DOSES_VAX_PCT FLOAT,

ADDITIONAL_DOSES_5PLUS BIGINT,
ADDITIONAL_DOSES_12PLUS BIGINT,
ADDITIONAL_DOSES_18PLUS BIGINT,
ADDITIONAL_DOSES_50PLUS BIGINT,
ADDITIONAL_DOSES_65PLUS BIGINT,

ADDITIONAL_DOSES_5PLUS_VAX_PCT FLOAT,
ADDITIONAL_DOSES_12PLUS_VAX_PCT FLOAT,
ADDITIONAL_DOSES_18PLUS_VAX_PCT FLOAT,
ADDITIONAL_DOSES_50PLUS_VAX_PCT FLOAT,
ADDITIONAL_DOSES_65PLUS_VAX_PCT FLOAT,

ADDITIONAL_DOSES_PFIZER BIGINT,
ADDITIONAL_DOSES_MODERNA BIGINT,
ADDITIONAL_DOSES_JANSSEN BIGINT,
ADDITIONAL_DOSES_UNK_MANUF BIGINT,

SECOND_BOOSTER BIGINT,
SECOND_BOOSTER_50PLUS BIGINT,
SECOND_BOOSTER_65PLUS BIGINT,

SECOND_BOOSTER_50PLUS_VAX_PCT FLOAT,
SECOND_BOOSTER_65PLUS_VAX_PCT FLOAT,

SECOND_BOOSTER_PFIZER BIGINT,
SECOND_BOOSTER_MODERNA BIGINT,
SECOND_BOOSTER_JANSSEN BIGINT,
SECOND_BOOSTER_UNK_MANUF BIGINT,

BIVALENT_BOOSTER_5PLUS BIGINT,
BIVALENT_BOOSTER_12PLUS BIGINT,
BIVALENT_BOOSTER_18PLUS BIGINT,
BIVALENT_BOOSTER_65PLUS BIGINT,

BIVALENT_BOOSTER_5PLUS_POP_PCT FLOAT,
BIVALENT_BOOSTER_12PLUS_POP_PCT FLOAT,
BIVALENT_BOOSTER_18PLUS_POP_PCT FLOAT,
BIVALENT_BOOSTER_65PLUS_POP_PCT FLOAT,

DISTRIBUTED BIGINT,
DISTRIBUTED_JANSSEN BIGINT,
DISTRIBUTED_MODERNA BIGINT,
DISTRIBUTED_PFIZER BIGINT,
DISTRIBUTED_NOVAVAX BIGINT,
DISTRIBUTED_UNK_MANUF BIGINT,

DIST_BIVALENT_MOD BIGINT,
DIST_BIVALENT_PFR BIGINT,

DIST_PER_100K FLOAT,
DISTRIBUTED_PER_100K_5PLUS FLOAT,
DISTRIBUTED_PER_100K_12PLUS FLOAT,
DISTRIBUTED_PER_100K_18PLUS FLOAT,
DISTRIBUTED_PER_100K_65PLUS FLOAT,

ADMIN_PER_100K FLOAT,
ADMIN_PER_100K_5PLUS FLOAT,
ADMIN_PER_100K_12PLUS FLOAT,
ADMIN_PER_100K_18PLUS FLOAT,
ADMIN_PER_100K_65PLUS FLOAT,

RECIP_ADMINISTERED BIGINT
    )
    """)


    snowflake.execute("""
    CREATE TABLE IF NOT EXISTS RAW.CENSUS_POPULATION (
        POPULATION INTEGER,
        STATE_NAME STRING,
        STATE_CODE STRING
    )
    """)


    snowflake.execute("""
    CREATE TABLE IF NOT EXISTS RAW.CDC_WEEKLY_CASES (
        DATE_UPDATED DATE,
        STATE STRING,
        START_DATE DATE,
        END_DATE DATE,

        TOT_CASES FLOAT,
        NEW_CASES FLOAT,
        TOT_DEATHS FLOAT,
        NEW_DEATHS FLOAT,

        NEW_HISTORIC_CASES INTEGER,
        NEW_HISTORIC_DEATHS INTEGER
    )
    """)

    snowflake.close()
    logger.info("Snowflake environment setup complete!")


def main():
    conn = snowflake.connector.connect(
        user=SNOWFLAKE_USER,
        password=SNOWFLAKE_PASSWORD,
        account=SNOWFLAKE_ACCOUNT,
        warehouse=SNOWFLAKE_WAREHOUSE
    )
    setup_snowflake_environment(conn)

    conn.close()


if __name__ == "__main__":
    main()