MERGE INTO {FINAL_TABLE} AS target
USING {STAGE_TABLE} AS source
ON target.STATE = source.STATE
   AND target.DATE_UPDATED = source.DATE_UPDATED

WHEN MATCHED THEN UPDATE SET
    TOT_CASES = source.TOT_CASES,
    TOT_DEATHS = source.TOT_DEATHS,
    NEW_CASES = source.NEW_CASES,
    NEW_DEATHS = source.NEW_DEATHS,
    NEW_HISTORIC_CASES = source.NEW_HISTORIC_CASES,
    NEW_HISTORIC_DEATHS = source.NEW_HISTORIC_DEATHS

WHEN NOT MATCHED THEN INSERT (
    STATE,
    DATE_UPDATED,
    TOT_CASES,
    TOT_DEATHS,
    NEW_CASES,
    NEW_DEATHS,
    NEW_HISTORIC_CASES,
    NEW_HISTORIC_DEATHS
) VALUES (
    source.STATE,
    source.DATE_UPDATED,
    source.TOT_CASES,
    source.TOT_DEATHS,
    source.NEW_CASES,
    source.NEW_DEATHS,
    source.NEW_HISTORIC_CASES,
    source.NEW_HISTORIC_DEATHS
);