MERGE INTO {FINAL_TABLE} AS target
USING {STAGE_TABLE} AS source
ON target.date = source.date
   AND target.location = source.location

WHEN MATCHED THEN UPDATE SET
    mmwr_week = source.mmwr_week,
    distributed = source.distributed,
    distributed_janssen = source.distributed_janssen,
    distributed_moderna = source.distributed_moderna,
    distributed_pfizer = source.distributed_pfizer,
    distributed_unk_manuf = source.distributed_unk_manuf,
    dist_per_100k = source.dist_per_100k,
    distributed_per_100k_12plus = source.distributed_per_100k_12plus,
    distributed_per_100k_18plus = source.distributed_per_100k_18plus,
    distributed_per_100k_65plus = source.distributed_per_100k_65plus,
    administered = source.administered,
    administered_12plus = source.administered_12plus,
    administered_18plus = source.administered_18plus,
    administered_65plus = source.administered_65plus,
    administered_janssen = source.administered_janssen,
    administered_moderna = source.administered_moderna,
    administered_pfizer = source.administered_pfizer,
    administered_unk_manuf = source.administered_unk_manuf,
    admin_per_100k = source.admin_per_100k,
    admin_per_100k_12plus = source.admin_per_100k_12plus,
    admin_per_100k_18plus = source.admin_per_100k_18plus,
    admin_per_100k_65plus = source.admin_per_100k_65plus,
    recip_administered = source.recip_administered,
    administered_dose1_recip = source.administered_dose1_recip,
    administered_dose1_pop_pct = source.administered_dose1_pop_pct,
    administered_dose1_recip_12plus = source.administered_dose1_recip_12plus,
    administered_dose1_recip_12pluspop_pct = source.administered_dose1_recip_12pluspop_pct,
    administered_dose1_recip_18plus = source.administered_dose1_recip_18plus,
    administered_dose1_recip_18pluspop_pct = source.administered_dose1_recip_18pluspop_pct,
    administered_dose1_recip_65plus = source.administered_dose1_recip_65plus,
    administered_dose1_recip_65pluspop_pct = source.administered_dose1_recip_65pluspop_pct,
    series_complete_yes = source.series_complete_yes,
    series_complete_pop_pct = source.series_complete_pop_pct,
    series_complete_12plus = source.series_complete_12plus,
    series_complete_12pluspop = source.series_complete_12pluspop,
    series_complete_18plus = source.series_complete_18plus,
    series_complete_18pluspop = source.series_complete_18pluspop,
    series_complete_65plus = source.series_complete_65plus,
    series_complete_65pluspop = source.series_complete_65pluspop,
    series_complete_janssen = source.series_complete_janssen,
    series_complete_moderna = source.series_complete_moderna,
    series_complete_pfizer = source.series_complete_pfizer,
    series_complete_unk_manuf = source.series_complete_unk_manuf,
    series_complete_janssen_12plus = source.series_complete_janssen_12plus,
    series_complete_moderna_12plus = source.series_complete_moderna_12plus,
    series_complete_pfizer_12plus = source.series_complete_pfizer_12plus,
    series_complete_unk_manuf_1 = source.series_complete_unk_manuf_1,
    series_complete_janssen_18plus = source.series_complete_janssen_18plus,
    series_complete_moderna_18plus = source.series_complete_moderna_18plus,
    series_complete_pfizer_18plus = source.series_complete_pfizer_18plus,
    series_complete_unk_manuf_2 = source.series_complete_unk_manuf_2,
    series_complete_janssen_65plus = source.series_complete_janssen_65plus,
    series_complete_moderna_65plus = source.series_complete_moderna_65plus,
    series_complete_pfizer_65plus = source.series_complete_pfizer_65plus,
    series_complete_unk_manuf_3 = source.series_complete_unk_manuf_3,
    additional_doses = source.additional_doses,
    additional_doses_vax_pct = source.additional_doses_vax_pct,
    additional_doses_18plus = source.additional_doses_18plus,
    additional_doses_18plus_vax_pct = source.additional_doses_18plus_vax_pct,
    additional_doses_50plus = source.additional_doses_50plus,
    additional_doses_50plus_vax_pct = source.additional_doses_50plus_vax_pct,
    additional_doses_65plus = source.additional_doses_65plus,
    additional_doses_65plus_vax_pct = source.additional_doses_65plus_vax_pct,
    additional_doses_moderna = source.additional_doses_moderna,
    additional_doses_pfizer = source.additional_doses_pfizer,
    additional_doses_janssen = source.additional_doses_janssen,
    additional_doses_unk_manuf = source.additional_doses_unk_manuf

WHEN NOT MATCHED THEN INSERT (
    date,
    mmwr_week,
    location,
    distributed,
    distributed_janssen,
    distributed_moderna,
    distributed_pfizer,
    distributed_unk_manuf,
    dist_per_100k,
    distributed_per_100k_12plus,
    distributed_per_100k_18plus,
    distributed_per_100k_65plus,
    administered,
    administered_12plus,
    administered_18plus,
    administered_65plus,
    administered_janssen,
    administered_moderna,
    administered_pfizer,
    administered_unk_manuf,
    admin_per_100k,
    admin_per_100k_12plus,
    admin_per_100k_18plus,
    admin_per_100k_65plus,
    recip_administered,
    administered_dose1_recip,
    administered_dose1_pop_pct,
    administered_dose1_recip_12plus,
    administered_dose1_recip_12pluspop_pct,
    administered_dose1_recip_18plus,
    administered_dose1_recip_18pluspop_pct,
    administered_dose1_recip_65plus,
    administered_dose1_recip_65pluspop_pct,
    series_complete_yes,
    series_complete_pop_pct,
    series_complete_12plus,
    series_complete_12pluspop,
    series_complete_18plus,
    series_complete_18pluspop,
    series_complete_65plus,
    series_complete_65pluspop,
    series_complete_janssen,
    series_complete_moderna,
    series_complete_pfizer,
    series_complete_unk_manuf,
    series_complete_janssen_12plus,
    series_complete_moderna_12plus,
    series_complete_pfizer_12plus,
    series_complete_unk_manuf_1,
    series_complete_janssen_18plus,
    series_complete_moderna_18plus,
    series_complete_pfizer_18plus,
    series_complete_unk_manuf_2,
    series_complete_janssen_65plus,
    series_complete_moderna_65plus,
    series_complete_pfizer_65plus,
    series_complete_unk_manuf_3,
    additional_doses,
    additional_doses_vax_pct,
    additional_doses_18plus,
    additional_doses_18plus_vax_pct,
    additional_doses_50plus,
    additional_doses_50plus_vax_pct,
    additional_doses_65plus,
    additional_doses_65plus_vax_pct,
    additional_doses_moderna,
    additional_doses_pfizer,
    additional_doses_janssen,
    additional_doses_unk_manuf
) VALUES (
    source.date,
    source.mmwr_week,
    source.location,
    source.distributed,
    source.distributed_janssen,
    source.distributed_moderna,
    source.distributed_pfizer,
    source.distributed_unk_manuf,
    source.dist_per_100k,
    source.distributed_per_100k_12plus,
    source.distributed_per_100k_18plus,
    source.distributed_per_100k_65plus,
    source.administered,
    source.administered_12plus,
    source.administered_18plus,
    source.administered_65plus,
    source.administered_janssen,
    source.administered_moderna,
    source.administered_pfizer,
    source.administered_unk_manuf,
    source.admin_per_100k,
    source.admin_per_100k_12plus,
    source.admin_per_100k_18plus,
    source.admin_per_100k_65plus,
    source.recip_administered,
    source.administered_dose1_recip,
    source.administered_dose1_pop_pct,
    source.administered_dose1_recip_12plus,
    source.administered_dose1_recip_12pluspop_pct,
    source.administered_dose1_recip_18plus,
    source.administered_dose1_recip_18pluspop_pct,
    source.administered_dose1_recip_65plus,
    source.administered_dose1_recip_65pluspop_pct,
    source.series_complete_yes,
    source.series_complete_pop_pct,
    source.series_complete_12plus,
    source.series_complete_12pluspop,
    source.series_complete_18plus,
    source.series_complete_18pluspop,
    source.series_complete_65plus,
    source.series_complete_65pluspop,
    source.series_complete_janssen,
    source.series_complete_moderna,
    source.series_complete_pfizer,
    source.series_complete_unk_manuf,
    source.series_complete_janssen_12plus,
    source.series_complete_moderna_12plus,
    source.series_complete_pfizer_12plus,
    source.series_complete_unk_manuf_1,
    source.series_complete_janssen_18plus,
    source.series_complete_moderna_18plus,
    source.series_complete_pfizer_18plus,
    source.series_complete_unk_manuf_2,
    source.series_complete_janssen_65plus,
    source.series_complete_moderna_65plus,
    source.series_complete_pfizer_65plus,
    source.series_complete_unk_manuf_3,
    source.additional_doses,
    source.additional_doses_vax_pct,
    source.additional_doses_18plus,
    source.additional_doses_18plus_vax_pct,
    source.additional_doses_50plus,
    source.additional_doses_50plus_vax_pct,
    source.additional_doses_65plus,
    source.additional_doses_65plus_vax_pct,
    source.additional_doses_moderna,
    source.additional_doses_pfizer,
    source.additional_doses_janssen,
    source.additional_doses_unk_manuf
);